#!/usr/bin/python

import json
import subprocess
import urllib2

fh = urllib2.urlopen('http://localhost:4001/v2/stats/self')
data = json.loads(fh.read())

if data['state'] == 'leader':
    fh = urllib2.urlopen('http://localhost:4001/v2/stats/leader')
    data.update(json.loads(fh.read()))

print(json.dumps(data, indent=2))
